---
ID: "fd66b241-2c1b-443b-9885-45bae3ef75ef"
Parent: "26eb5699-6620-4c40-83dd-6f523113e6a6"
Template: "26eb5699-6620-4c40-83dd-6f523113e6a6"
Path: /sitecore/templates/Project/Basic/Headless Tenant/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230411T170629Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\79hNWxfoQm
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\79hNWxfoQm
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "75a703b2-1744-4537-8cc3-8da6824fba72"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\79hNWxfoQm
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230411T170629Z
