---
ID: "a2c58dd9-17fb-477c-b574-160430bdd441"
Parent: "9edd888e-f895-4606-9d91-1ac406c4c599"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: /sitecore/content/Martin/Martin/Settings/Shared Sites Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230413T194721Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\79hNWxfoQm
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\79hNWxfoQm
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8a851001-fa23-4411-a2f0-ce085088f8f2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\79hNWxfoQm
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230413T194721Z
